name: ${project.name}
version: ${project.version}
main: io.josemmo.bukkit.plugin.YamipaPlugin
api-version: 1.13
depend: [NBTAPI, ProtocolLib]

permissions:
  yamipa.*:
    default: op
    children:
      yamipa.list: true
      yamipa.download: true
      yamipa.place: true
      yamipa.remove: true
      yamipa.remove.radius: true
  yamipa.list:
    default: op
  yamipa.download:
    default: op
  yamipa.place:
    default: op
  yamipa.remove:
    default: op
  yamipa.remove.radius:
    default: op
