name: ${project.name}
version: ${project.version}
main: io.josemmo.bukkit.plugin.YamipaPlugin
api-version: 1.16
depend: [ProtocolLib]
softdepend: [Multiverse-Core, Hyperverse, My_Worlds]

permissions:
  yamipa.*:
    default: op
    children:
      yamipa.clear: true
      yamipa.describe: true
      yamipa.download: true
      yamipa.give: true
      yamipa.list: true
      yamipa.place: true
      yamipa.remove: true
      yamipa.top: true
  yamipa.clear:
    default: op
  yamipa.describe:
    default: op
  yamipa.download:
    default: op
  yamipa.give:
    default: op
  yamipa.list:
    default: op
  yamipa.place:
    default: op
  yamipa.remove:
    default: op
  yamipa.top:
    default: op
